In [1]:
!pip install python-terrier

Collecting python-terrier
  Using cached python_terrier-0.13.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from python-terrier) (1.26.4)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (from python-terrier) (2.2.2)
Collecting more-itertools (from python-terrier)
  Using cached more_itertools-10.8.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from python-terrier) (4.66.4)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from python-terrier) (2.31.0)
Collecting ir-datasets>=0.3.2 (from python-terrier)
  Using cached ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Collecting pyjnius>=1.4.2 (from python-terrier)
  Using cached pyjnius-1.7.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting deprecated (from python-terrier)
  Using cached Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: scipy in /opt/conda/lib/python3.11/site-packages (from python-terrier) (1.13.0)
Collecting ir-measures>=0.3.1 (from python-terrier)
  Using cached ir_measures-0.4.1-py3-none-any.whl.metadata (7.0 kB)
Collecting pytrec-eval-terrier>=0.5.3 (from python-terrier)
  Using cached pytrec_eval_terrier-0.5.9-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from python-terrier) (3.1.4)
Requirement already satisfied: statsmodels in /opt/conda/lib/python3.11/site-packages (from python-terrier) (0.14.2)
Requirement already satisfied: dill in /opt/conda/lib/python3.11/site-packages (from python-terrier) (0.3.8)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from python-terrier) (1.4.2)
Collecting chest (from python-terrier)
  Using cached chest-0.2.3-py3-none-any.whl
Requirement already satisfied: lz4 in /opt/conda/lib/python3.11/site-packages (from python-terrier) (4.3.3)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /opt/conda/lib/python3.11/site-packages (from ir-datasets>=0.3.2->python-terrier) (4.12.3)
Collecting inscriptis>=2.2.0 (from ir-datasets>=0.3.2->python-terrier)
  Using cached inscriptis-2.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: lxml>=4.5.2 in /opt/conda/lib/python3.11/site-packages (from ir-datasets>=0.3.2->python-terrier) (5.3.1)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/conda/lib/python3.11/site-packages (from ir-datasets>=0.3.2->python-terrier) (6.0.1)
Collecting trec-car-tools>=2.5.4 (from ir-datasets>=0.3.2->python-terrier)
  Using cached trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir-datasets>=0.3.2->python-terrier)
  Using cached warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir-datasets>=0.3.2->python-terrier)
  Using cached warc3_wet_clueweb09-0.2.5-py3-none-any.whl
Collecting zlib-state>=0.1.3 (from ir-datasets>=0.3.2->python-terrier)
  Using cached zlib_state-0.1.10-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir-datasets>=0.3.2->python-terrier)
  Using cached ijson-3.4.0.post0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir-datasets>=0.3.2->python-terrier)
  Using cached unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in /opt/conda/lib/python3.11/site-packages (from ir-datasets>=0.3.2->python-terrier) (16.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->python-terrier) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->python-terrier) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->python-terrier) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->python-terrier) (2025.1.31)
Collecting heapdict (from chest->python-terrier)
  Using cached HeapDict-1.0.1-py3-none-any.whl.metadata (1.9 kB)
Collecting wrapt<2,>=1.10 (from deprecated->python-terrier)
  Using cached wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->python-terrier) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas->python-terrier) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas->python-terrier) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas->python-terrier) (2024.1)
Requirement already satisfied: patsy>=0.5.6 in /opt/conda/lib/python3.11/site-packages (from statsmodels->python-terrier) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.11/site-packages (from statsmodels->python-terrier) (24.2)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.11/site-packages (from beautifulsoup4>=4.4.1->ir-datasets>=0.3.2->python-terrier) (2.5)
Collecting requests (from python-terrier)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: six in /opt/conda/lib/python3.11/site-packages (from patsy>=0.5.6->statsmodels->python-terrier) (1.16.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir-datasets>=0.3.2->python-terrier)
  Using cached cbor-1.0.0-cp311-cp311-linux_x86_64.whl
Using cached python_terrier-0.13.1-py3-none-any.whl (167 kB)
Using cached ir_datasets-0.5.11-py3-none-any.whl (866 kB)
Using cached ir_measures-0.4.1-py3-none-any.whl (61 kB)
Using cached pyjnius-1.7.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
Using cached pytrec_eval_terrier-0.5.9-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (304 kB)
Using cached Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)
Using cached more_itertools-10.8.0-py3-none-any.whl (69 kB)
Using cached ijson-3.4.0.post0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (134 kB)
Using cached inscriptis-2.6.0-py3-none-any.whl (45 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Using cached unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Using cached warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Using cached wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (82 kB)
Using cached zlib_state-0.1.10-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (21 kB)
Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Installing collected packages: warc3-wet-clueweb09, warc3-wet, pyjnius, heapdict, cbor, zlib-state, wrapt, unlzw3, trec-car-tools, requests, more-itertools, ijson, chest, pytrec-eval-terrier, inscriptis, deprecated, ir-measures, ir-datasets, python-terrier
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
Successfully installed cbor-1.0.0 chest-0.2.3 deprecated-1.2.18 heapdict-1.0.1 ijson-3.4.0.post0 inscriptis-2.6.0 ir-datasets-0.5.11 ir-measures-0.4.1 more-itertools-10.8.0 pyjnius-1.7.0 python-terrier-0.13.1 pytrec-eval-terrier-0.5.9 requests-2.32.5 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 wrapt-1.17.3 zlib-state-0.1.10

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [2]:
!wget -r -l 3 https://paulgraham.com/articles.html

--2025-10-14 16:05:30--  https://paulgraham.com/articles.html
Resolving paulgraham.com (paulgraham.com)... 52.204.244.237, 52.4.160.184
Connecting to paulgraham.com (paulgraham.com)|52.204.244.237|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/articles.html’

paulgraham.com/arti     [ <=>                ] 114.26K   614KB/s    in 0.2s

2025-10-14 16:05:30 (614 KB/s) - ‘paulgraham.com/articles.html’ saved [116999]

Loading robots.txt; please ignore errors.
--2025-10-14 16:05:30--  https://paulgraham.com/robots.txt
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘paulgraham.com/robots.txt’

paulgraham.com/robo     [ <=>                ]     265  --.-KB/s    in 0s

2025-10-14 16:05:30 (16.1 MB/s) - ‘paulgraham.com/robots.txt’ saved [265]

--2025-10-14 16:05:30--  https://paulgraham.com/index.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/index.html’

paulgraham.com/inde     [ <=>                ]   7.78K  --.-KB/s    in 0s

2025-10-14 16:05:30 (93.3 MB/s) - ‘paulgraham.com/index.html’ saved [7966]

--2025-10-14 16:05:30--  https://paulgraham.com/books.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/books.html’

paulgraham.com/book     [ <=>                ]   7.72K  --.-KB/s    in 0s

2025-10-14 16:05:30 (90.7 MB/s) - ‘paulgraham.com/books.html’ saved [7903]

--2025-10-14 16:05:30--  https://paulgraham.com/arc.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/arc.html’

paulgraham.com/arc.     [ <=>                ]  15.19K  --.-KB/s    in 0.008s

2025-10-14 16:05:30 (1.88 MB/s) - ‘paulgraham.com/arc.html’ saved [15557]

--2025-10-14 16:05:30--  https://paulgraham.com/bel.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/bel.html’

paulgraham.com/bel.     [ <=>                ]   6.72K  --.-KB/s    in 0s

2025-10-14 16:05:31 (108 MB/s) - ‘paulgraham.com/bel.html’ saved [6885]

--2025-10-14 16:05:31--  https://paulgraham.com/lisp.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/lisp.html’

paulgraham.com/lisp     [ <=>                ]  10.94K  --.-KB/s    in 0.009s

2025-10-14 16:05:31 (1.24 MB/s) - ‘paulgraham.com/lisp.html’ saved [11206]

--2025-10-14 16:05:31--  https://paulgraham.com/antispam.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/antispam.html’

paulgraham.com/anti     [ <=>                ]  16.16K  --.-KB/s    in 0.01s

2025-10-14 16:05:31 (1.63 MB/s) - ‘paulgraham.com/antispam.html’ saved [16543]

--2025-10-14 16:05:31--  https://paulgraham.com/kedrosky.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/kedrosky.html’

paulgraham.com/kedr     [ <=>                ]   8.27K  --.-KB/s    in 0s

2025-10-14 16:05:31 (87.2 MB/s) - ‘paulgraham.com/kedrosky.html’ saved [8473]

--2025-10-14 16:05:31--  https://paulgraham.com/faq.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/faq.html’

paulgraham.com/faq.     [ <=>                ]  10.34K  --.-KB/s    in 0.002s

2025-10-14 16:05:31 (4.92 MB/s) - ‘paulgraham.com/faq.html’ saved [10587]

--2025-10-14 16:05:31--  https://paulgraham.com/raq.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/raq.html’

paulgraham.com/raq.     [ <=>                ]  11.92K  --.-KB/s    in 0.004s

2025-10-14 16:05:31 (3.24 MB/s) - ‘paulgraham.com/raq.html’ saved [12207]

--2025-10-14 16:05:31--  https://paulgraham.com/quo.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/quo.html’

paulgraham.com/quo.     [ <=>                ] 139.59K  --.-KB/s    in 0.06s

2025-10-14 16:05:31 (2.19 MB/s) - ‘paulgraham.com/quo.html’ saved [142937]

--2025-10-14 16:05:31--  https://paulgraham.com/rss.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/rss.html’

paulgraham.com/rss.     [ <=>                ]   5.96K  --.-KB/s    in 0s

2025-10-14 16:05:31 (37.6 MB/s) - ‘paulgraham.com/rss.html’ saved [6106]

--2025-10-14 16:05:31--  https://paulgraham.com/bio.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/bio.html’

paulgraham.com/bio.     [ <=>                ]   7.68K  --.-KB/s    in 0s

2025-10-14 16:05:31 (87.5 MB/s) - ‘paulgraham.com/bio.html’ saved [7861]

Loading robots.txt; please ignore errors.
--2025-10-14 16:05:31--  http://paulgraham.com/robots.txt
Connecting to paulgraham.com (paulgraham.com)|52.204.244.237|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘paulgraham.com/robots.txt’

paulgraham.com/robo     [ <=>                ]     265  --.-KB/s    in 0s

2025-10-14 16:05:31 (13.5 MB/s) - ‘paulgraham.com/robots.txt’ saved [265]

--2025-10-14 16:05:31--  https://paulgraham.com/greatwork.html
Connecting to paulgraham.com (paulgraham.com)|52.204.244.237|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/greatwork.html’

paulgraham.com/grea     [   <=>              ]  77.90K   104KB/s    in 0.7s

2025-10-14 16:05:33 (104 KB/s) - ‘paulgraham.com/greatwork.html’ saved [79765]

--2025-10-14 16:05:33--  https://paulgraham.com/kids.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/kids.html’

paulgraham.com/kids     [ <=>                ]  15.31K  --.-KB/s    in 0.06s

2025-10-14 16:05:33 (249 KB/s) - ‘paulgraham.com/kids.html’ saved [15673]

--2025-10-14 16:05:33--  https://paulgraham.com/selfindulgence.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/selfindulgence.html’

paulgraham.com/self     [ <=>                ]   9.60K  --.-KB/s    in 0s

2025-10-14 16:05:33 (26.1 MB/s) - ‘paulgraham.com/selfindulgence.html’ saved [9831]

--2025-10-14 16:05:33--  https://paulgraham.com/field.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/field.html’

paulgraham.com/fiel     [ <=>                ]  10.41K  --.-KB/s    in 0.002s

2025-10-14 16:05:33 (5.75 MB/s) - ‘paulgraham.com/field.html’ saved [10664]

--2025-10-14 16:05:33--  https://paulgraham.com/goodwriting.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/goodwriting.html’

paulgraham.com/good     [ <=>                ]  15.45K  --.-KB/s    in 0.01s

2025-10-14 16:05:33 (1.59 MB/s) - ‘paulgraham.com/goodwriting.html’ saved [15823]

--2025-10-14 16:05:33--  https://paulgraham.com/do.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/do.html’

paulgraham.com/do.h     [ <=>                ]  14.96K  --.-KB/s    in 0.003s

2025-10-14 16:05:33 (5.24 MB/s) - ‘paulgraham.com/do.html’ saved [15315]

--2025-10-14 16:05:33--  https://paulgraham.com/woke.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/woke.html’

paulgraham.com/woke     [ <=>                ]  45.63K  --.-KB/s    in 0.1s

2025-10-14 16:05:33 (369 KB/s) - ‘paulgraham.com/woke.html’ saved [46723]

--2025-10-14 16:05:33--  https://paulgraham.com/writes.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/writes.html’

paulgraham.com/writ     [ <=>                ]   9.06K  --.-KB/s    in 0.001s

2025-10-14 16:05:33 (15.3 MB/s) - ‘paulgraham.com/writes.html’ saved [9280]

--2025-10-14 16:05:33--  https://paulgraham.com/when.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/when.html’

paulgraham.com/when     [ <=>                ]  14.98K  --.-KB/s    in 0.004s

2025-10-14 16:05:33 (3.47 MB/s) - ‘paulgraham.com/when.html’ saved [15339]

--2025-10-14 16:05:33--  https://paulgraham.com/foundermode.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/foundermode.html’

paulgraham.com/foun     [ <=>                ]  13.14K  --.-KB/s    in 0.009s

2025-10-14 16:05:33 (1.46 MB/s) - ‘paulgraham.com/foundermode.html’ saved [13457]

--2025-10-14 16:05:33--  https://paulgraham.com/persistence.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/persistence.html’

paulgraham.com/pers     [ <=>                ]  18.17K  --.-KB/s    in 0.004s

2025-10-14 16:05:34 (4.02 MB/s) - ‘paulgraham.com/persistence.html’ saved [18608]

--2025-10-14 16:05:34--  https://paulgraham.com/reddits.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/reddits.html’

paulgraham.com/redd     [ <=>                ]  12.14K  --.-KB/s    in 0.009s

2025-10-14 16:05:34 (1.26 MB/s) - ‘paulgraham.com/reddits.html’ saved [12435]

--2025-10-14 16:05:34--  https://paulgraham.com/google.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/google.html’

paulgraham.com/goog     [ <=>                ]  21.95K  --.-KB/s    in 0.009s

2025-10-14 16:05:34 (2.32 MB/s) - ‘paulgraham.com/google.html’ saved [22477]

--2025-10-14 16:05:34--  https://paulgraham.com/best.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/best.html’

paulgraham.com/best     [ <=>                ]  32.04K  --.-KB/s    in 0.06s

2025-10-14 16:05:34 (520 KB/s) - ‘paulgraham.com/best.html’ saved [32811]

--2025-10-14 16:05:34--  https://paulgraham.com/superlinear.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/superlinear.html’

paulgraham.com/supe     [ <=>                ]  32.68K  --.-KB/s    in 0.06s

2025-10-14 16:05:34 (533 KB/s) - ‘paulgraham.com/superlinear.html’ saved [33468]

--2025-10-14 16:05:34--  https://paulgraham.com/getideas.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/getideas.html’

paulgraham.com/geti     [ <=>                ]   6.63K  --.-KB/s    in 0s

2025-10-14 16:05:34 (114 MB/s) - ‘paulgraham.com/getideas.html’ saved [6791]

--2025-10-14 16:05:34--  https://paulgraham.com/read.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/read.html’

paulgraham.com/read     [ <=>                ]  10.76K  --.-KB/s    in 0.003s

2025-10-14 16:05:34 (3.10 MB/s) - ‘paulgraham.com/read.html’ saved [11020]

--2025-10-14 16:05:34--  https://paulgraham.com/want.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/want.html’

paulgraham.com/want     [ <=>                ]   9.66K  --.-KB/s    in 0s

2025-10-14 16:05:34 (69.1 MB/s) - ‘paulgraham.com/want.html’ saved [9889]

--2025-10-14 16:05:34--  https://paulgraham.com/alien.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/alien.html’

paulgraham.com/alie     [ <=>                ]   9.69K  --.-KB/s    in 0.002s

2025-10-14 16:05:34 (5.00 MB/s) - ‘paulgraham.com/alien.html’ saved [9927]

--2025-10-14 16:05:34--  https://paulgraham.com/users.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/users.html’

paulgraham.com/user     [ <=>                ]  19.32K  --.-KB/s    in 0.06s

2025-10-14 16:05:35 (315 KB/s) - ‘paulgraham.com/users.html’ saved [19783]

--2025-10-14 16:05:35--  https://paulgraham.com/heresy.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/heresy.html’

paulgraham.com/here     [ <=>                ]  19.32K  --.-KB/s    in 0.007s

2025-10-14 16:05:35 (2.82 MB/s) - ‘paulgraham.com/heresy.html’ saved [19781]

--2025-10-14 16:05:35--  https://paulgraham.com/words.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/words.html’

paulgraham.com/word     [ <=>                ]  13.41K  --.-KB/s    in 0.01s

2025-10-14 16:05:35 (1.34 MB/s) - ‘paulgraham.com/words.html’ saved [13733]

--2025-10-14 16:05:35--  https://paulgraham.com/goodtaste.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/goodtaste.html’

paulgraham.com/good     [ <=>                ]  12.01K  --.-KB/s    in 0.003s

2025-10-14 16:05:35 (4.20 MB/s) - ‘paulgraham.com/goodtaste.html’ saved [12297]

--2025-10-14 16:05:35--  https://paulgraham.com/smart.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/smart.html’

paulgraham.com/smar     [ <=>                ]  14.78K  --.-KB/s    in 0.003s

2025-10-14 16:05:35 (5.65 MB/s) - ‘paulgraham.com/smart.html’ saved [15135]

--2025-10-14 16:05:35--  https://paulgraham.com/weird.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/weird.html’

paulgraham.com/weir     [ <=>                ]   8.63K  --.-KB/s    in 0.004s

2025-10-14 16:05:35 (1.89 MB/s) - ‘paulgraham.com/weird.html’ saved [8838]

--2025-10-14 16:05:35--  https://paulgraham.com/hwh.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/hwh.html’

paulgraham.com/hwh.     [ <=>                ]  25.94K  --.-KB/s    in 0.06s

2025-10-14 16:05:36 (422 KB/s) - ‘paulgraham.com/hwh.html’ saved [26558]

--2025-10-14 16:05:36--  https://paulgraham.com/own.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/own.html’

paulgraham.com/own.     [ <=>                ]  20.62K  --.-KB/s    in 0.009s

2025-10-14 16:05:36 (2.13 MB/s) - ‘paulgraham.com/own.html’ saved [21118]

--2025-10-14 16:05:36--  https://paulgraham.com/fn.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/fn.html’

paulgraham.com/fn.h     [ <=>                ]  14.52K  --.-KB/s    in 0.008s

2025-10-14 16:05:36 (1.70 MB/s) - ‘paulgraham.com/fn.html’ saved [14866]

--2025-10-14 16:05:36--  https://paulgraham.com/newideas.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/newideas.html’

paulgraham.com/newi     [ <=>                ]  14.26K  --.-KB/s    in 0.003s

2025-10-14 16:05:36 (4.36 MB/s) - ‘paulgraham.com/newideas.html’ saved [14598]

--2025-10-14 16:05:36--  https://paulgraham.com/nft.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/nft.html’

paulgraham.com/nft.     [ <=>                ]   7.66K  --.-KB/s    in 0s

2025-10-14 16:05:36 (78.5 MB/s) - ‘paulgraham.com/nft.html’ saved [7844]

--2025-10-14 16:05:36--  https://paulgraham.com/real.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/real.html’

paulgraham.com/real     [ <=>                ]  12.97K  --.-KB/s    in 0.003s

2025-10-14 16:05:36 (3.71 MB/s) - ‘paulgraham.com/real.html’ saved [13281]

--2025-10-14 16:05:36--  https://paulgraham.com/richnow.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/richnow.html’

paulgraham.com/rich     [ <=>                ]  22.25K  --.-KB/s    in 0.003s

2025-10-14 16:05:36 (7.29 MB/s) - ‘paulgraham.com/richnow.html’ saved [22780]

--2025-10-14 16:05:36--  https://paulgraham.com/simply.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/simply.html’

paulgraham.com/simp     [ <=>                ]   8.71K  --.-KB/s    in 0.001s

2025-10-14 16:05:36 (6.70 MB/s) - ‘paulgraham.com/simply.html’ saved [8919]

--2025-10-14 16:05:36--  https://paulgraham.com/donate.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/donate.html’

paulgraham.com/dona     [ <=>                ]   8.84K  --.-KB/s    in 0s

2025-10-14 16:05:36 (39.3 MB/s) - ‘paulgraham.com/donate.html’ saved [9050]

--2025-10-14 16:05:36--  https://paulgraham.com/worked.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/worked.html’

paulgraham.com/work     [ <=>                ]  83.49K   452KB/s    in 0.2s

2025-10-14 16:05:37 (452 KB/s) - ‘paulgraham.com/worked.html’ saved [85497]

--2025-10-14 16:05:37--  https://paulgraham.com/earnest.html
Reusing existing connection to paulgraham.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘paulgraham.com/earnest.html’

paulgraham.com/earn     [ <=>                ]  16.49K  --.-KB/s    in 0.003s

2025-10-14 16:05:37 (5.14 MB/s) - ‘paulgraham.com/earnest.html’ saved [16887]

--2025-10-14 16:05:37--  https://paulgraham.com/ace.html
Reusing existing connection to paulgraham.com:443.

In [3]:
import os
os.environ["JAVA_HOME"] = "/home/jovyan/jdk-11"
os.environ["JVM_PATH"] = "/home/jovyan/jdk-11/lib/server/libjvm.so"

import pyterrier as pt
if not pt.started():
  pt.init()

/tmp/ipykernel_270/1452397746.py:6: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_270/1452397746.py:7: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [4]:
files = pt.io.find_files("paulgraham.com")
indexer = pt.FilesIndexer("./pg_index", verbose=True, blocks=False)
indexref = indexer.index(files)
index = pt.IndexFactory.of(indexref)
print (index.getCollectionStatistics().toString())

Number of documents: 375
Number of terms: 12417
Number of postings: 160866
Number of fields: 0
Number of tokens: 414014
Field names: []
Positions:   false

In [5]:
import pandas as pd

In [6]:
queries = pd.DataFrame([["q1","essay"], ["q2","founders"]], columns=["qid","query"])

In [7]:
queries

  qid     query
0  q1     essay
1  q2  founders

In [8]:
index = pt.IndexFactory.of("./pg_index/data.properties")
tf_idf = pt.BatchRetrieve(index, wmodel="TF_IDF")
tf_idf.transform(queries)

/tmp/ipykernel_270/2793904222.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tf_idf = pt.BatchRetrieve(index, wmodel="TF_IDF")

    qid  docid docno  rank     score     query
0    q1     45   d46     0  2.382730     essay
1    q1    341  d342     1  2.340775     essay
2    q1     94   d95     2  2.335580     essay
3    q1    188  d189     3  2.331596     essay
4    q1    225  d226     4  2.302924     essay
..   ..    ...   ...   ...       ...       ...
248  q2     62   d63   127  0.803749  founders
249  q2     20   d21   128  0.792604  founders
250  q2    230  d231   129  0.741212  founders
251  q2    122  d123   130  0.672493  founders
252  q2    247  d248   131  0.526442  founders

[253 rows x 6 columns]